## Now we are going to take the clean data and apply encoder and decoder

In [21]:
%pip install langchain_openai
from langchain_community.document_loaders import TextLoader
from langchain_text_splitters import CharacterTextSplitter
from langchain_chroma import Chroma
from langchain_ollama import OllamaEmbeddings

Requirement already satisfied: langchain_openai in c:\users\ivan\appdata\local\anaconda3\lib\site-packages (0.3.33)
Requirement already satisfied: langchain-core<1.0.0,>=0.3.76 in c:\users\ivan\appdata\local\anaconda3\lib\site-packages (from langchain_openai) (0.3.76)
Requirement already satisfied: openai<2.0.0,>=1.104.2 in c:\users\ivan\appdata\local\anaconda3\lib\site-packages (from langchain_openai) (1.109.0)
Requirement already satisfied: tiktoken<1,>=0.7 in c:\users\ivan\appdata\local\anaconda3\lib\site-packages (from langchain_openai) (0.11.0)
Requirement already satisfied: langsmith>=0.3.45 in c:\users\ivan\appdata\local\anaconda3\lib\site-packages (from langchain-core<1.0.0,>=0.3.76->langchain_openai) (0.4.29)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in c:\users\ivan\appdata\local\anaconda3\lib\site-packages (from langchain-core<1.0.0,>=0.3.76->langchain_openai) (9.0.0)
Requirement already satisfied: jsonpatch<2.0,>=1.33 in c:\users\ivan\appdata\local\anaconda3\lib\site-packages (from langchain-core<1.0.0,>=0.3.76->langchain_openai) (1.33)
Requirement already satisfied: PyYAML>=5.3 in c:\users\ivan\appdata\local\anaconda3\lib\site-packages (from langchain-core<1.0.0,>=0.3.76->langchain_openai) (6.0.2)
Requirement already satisfied: typing-extensions>=4.7 in c:\users\ivan\appdata\local\anaconda3\lib\site-packages (from langchain-core<1.0.0,>=0.3.76->langchain_openai) (4.12.2)
Requirement already satisfied: packaging>=23.2 in c:\users\ivan\appdata\local\anaconda3\lib\site-packages (from langchain-core<1.0.0,>=0.3.76->langchain_openai) (24.2)
Requirement already satisfied: pydantic>=2.7.4 in c:\users\ivan\appdata\local\anaconda3\lib\site-packages (from langchain-core<1.0.0,>=0.3.76->langchain_openai) (2.10.3)
Requirement already satisfied: jsonpointer>=1.9 in c:\users\ivan\appdata\local\anaconda3\lib\site-packages (from jsonpatch<2.0,>=1.33->langchain-core<1.0.0,>=0.3.76->langchain_openai) (2.1)
Requirement already satisfied: anyio<5,>=3.5.0 in c:\users\ivan\appdata\local\anaconda3\lib\site-packages (from openai<2.0.0,>=1.104.2->langchain_openai) (4.7.0)
Requirement already satisfied: distro<2,>=1.7.0 in c:\users\ivan\appdata\local\anaconda3\lib\site-packages (from openai<2.0.0,>=1.104.2->langchain_openai) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\ivan\appdata\local\anaconda3\lib\site-packages (from openai<2.0.0,>=1.104.2->langchain_openai) (0.28.1)
Requirement already satisfied: jiter<1,>=0.4.0 in c:\users\ivan\appdata\local\anaconda3\lib\site-packages (from openai<2.0.0,>=1.104.2->langchain_openai) (0.11.0)
Requirement already satisfied: sniffio in c:\users\ivan\appdata\local\anaconda3\lib\site-packages (from openai<2.0.0,>=1.104.2->langchain_openai) (1.3.0)
Requirement already satisfied: tqdm>4 in c:\users\ivan\appdata\local\anaconda3\lib\site-packages (from openai<2.0.0,>=1.104.2->langchain_openai) (4.67.1)
Requirement already satisfied: idna>=2.8 in c:\users\ivan\appdata\local\anaconda3\lib\site-packages (from anyio<5,>=3.5.0->openai<2.0.0,>=1.104.2->langchain_openai) (3.7)
Requirement already satisfied: certifi in c:\users\ivan\appdata\local\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->openai<2.0.0,>=1.104.2->langchain_openai) (2025.4.26)
Requirement already satisfied: httpcore==1.* in c:\users\ivan\appdata\local\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->openai<2.0.0,>=1.104.2->langchain_openai) (1.0.9)
Requirement already satisfied: h11>=0.16 in c:\users\ivan\appdata\local\anaconda3\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai<2.0.0,>=1.104.2->langchain_openai) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\ivan\appdata\local\anaconda3\lib\site-packages (from pydantic>=2.7.4->langchain-core<1.0.0,>=0.3.76->langchain_openai) (0.6.0)
Requirement already satisfied: pydantic-core==2.27.1 in c:\users\ivan\appdata\local\anaconda3\lib\site-packages (from pydantic>=2.7.4->langchain-core<1.0.0,>=0.3.76->langchain_openai) (2.27.1)
Requirement already satisfied: regex>=2022.1.18 in c:\users\ivan\appdata\local\anaconda3\lib\site-packages (from tiktoken<1,>=0.7->langchain_openai) (2024.11.6)
Requirement already satisfied: requests>=2.26.0 in c:\users\ivan\appdata\local\anaconda3\lib\site-packages (from tiktoken<1,>=0.7->langchain_openai) (2.32.5)
Requirement already satisfied: orjson>=3.9.14 in c:\users\ivan\appdata\local\anaconda3\lib\site-packages (from langsmith>=0.3.45->langchain-core<1.0.0,>=0.3.76->langchain_openai) (3.11.3)
Requirement already satisfied: requests-toolbelt>=1.0.0 in c:\users\ivan\appdata\local\anaconda3\lib\site-packages (from langsmith>=0.3.45->langchain-core<1.0.0,>=0.3.76->langchain_openai) (1.0.0)
Requirement already satisfied: zstandard>=0.23.0 in c:\users\ivan\appdata\local\anaconda3\lib\site-packages (from langsmith>=0.3.45->langchain-core<1.0.0,>=0.3.76->langchain_openai) (0.23.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\ivan\appdata\local\anaconda3\lib\site-packages (from requests>=2.26.0->tiktoken<1,>=0.7->langchain_openai) (3.3.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\ivan\appdata\local\anaconda3\lib\site-packages (from requests>=2.26.0->tiktoken<1,>=0.7->langchain_openai) (2.3.0)
Requirement already satisfied: colorama in c:\users\ivan\appdata\local\anaconda3\lib\site-packages (from tqdm>4->openai<2.0.0,>=1.104.2->langchain_openai) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

## Get the list of books

In [22]:
import pandas as pd

books = pd.read_csv("books_cleaned.csv")

In [3]:
books.head()

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description
0,9780002005883,0002005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,361.0,Gilead,9780002005883 A NOVEL THAT READERS and critics...
1,9780002261982,0002261987,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,5164.0,Spider's Web: A Novel,9780002261982 A new 'Christie for Christmas' -...
2,9780006178736,0006178731,Rage of angels,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,29532.0,Rage of angels,"9780006178736 A memorable, mesmerizing heroine..."
3,9780006280897,0006280897,The Four Loves,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,4.15,170.0,33684.0,The Four Loves,9780006280897 Lewis' work on the nature of lov...
4,9780006280934,0006280935,The Problem of Pain,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=Kk-uV...,"""In The Problem of Pain, C.S. Lewis, one of th...",2002.0,4.09,176.0,37569.0,The Problem of Pain,"9780006280934 ""In The Problem of Pain, C.S. Le..."

In [20]:
books.shape

(5197, 13)

## Mapper columns to txt.

* Adding only description

In [21]:
with open("tagged_description.txt", "w", encoding="utf-8") as f:
    for description in books["tagged_description"]:
        f.write(str(description) + "\n")

In [9]:
from langchain_community.document_loaders import TextLoader
from langchain_text_splitters import CharacterTextSplitter
raw_documents = TextLoader("tagged_description.txt").load()
text_splitter = CharacterTextSplitter(chunk_size=1, chunk_overlap=0, separator="\n")
documents = text_splitter.split_documents(raw_documents)

Created a chunk of size 1168, which is longer than the specified 1
Created a chunk of size 1214, which is longer than the specified 1

Created a chunk of size 373, which is longer than the specified 1
Created a chunk of size 309, which is longer than the specified 1
Created a chunk of size 479, which is longer than the specified 1
Created a chunk of size 482, which is longer than the specified 1
Created a chunk of size 960, which is longer than the specified 1
Created a chunk of size 188, which is longer than the specified 1
Created a chunk of size 843, which is longer than the specified 1
Created a chunk of size 284, which is longer than the specified 1
Created a chunk of size 193, which is longer than the specified 1
Created a chunk of size 877, which is longer than the specified 1
Created a chunk of size 1088, which is longer than the specified 1
Created a chunk of size 1189, which is longer than the specified 1
Created a chunk of size 304, which is longer than the specified 1
Created a chunk of size 270, which is longer than the specified 1
Created a chunk of size 211, which is longer than the specified 1
Created a chunk of size 214, which is longer than the specified 1
Created a chunk of size 513, which is longer than the specified 1
Created a chunk of size 752, which is longer than the specified 1
Created a chunk of size 388, which is longer than the specified 1
Created a chunk of size 263, which is longer than the specified 1
Created a chunk of size 247, which is longer than the specified 1
Created a chunk of size 306, which is longer than the specified 1
Created a chunk of size 728, which is longer than the specified 1
Created a chunk of size 721, which is longer than the specified 1
Created a chunk of size 256, which is longer than the specified 1
Created a chunk of size 473, which is longer than the specified 1
Created a chunk of size 270, which is longer than the specified 1
Created a chunk of size 1253, which is longer than the specified 1
Created a chunk of size 681, which is longer than the specified 1
Created a chunk of size 239, which is longer than the specified 1
Created a chunk of size 553, which is longer than the specified 1
Created a chunk of size 521, which is longer than the specified 1
Created a chunk of size 280, which is longer than the specified 1
Created a chunk of size 787, which is longer than the specified 1
Created a chunk of size 564, which is longer than the specified 1
Created a chunk of size 523, which is longer than the specified 1
Created a chunk of size 177, which is longer than the specified 1
Created a chunk of size 297, which is longer than the specified 1
Created a chunk of size 533, which is longer than the specified 1
Created a chunk of size 559, which is longer than the specified 1
Created a chunk of size 563, which is longer than the specified 1
Created a chunk of size 382, which is longer than the specified 1
Created a chunk of size 410, which is longer than the specified 1
Created a chunk of size 461, which is longer than the specified 1
Created a chunk of size 595, which is longer than the specified 1
Created a chunk of size 476, which is longer than the specified 1
Created a chunk of size 459, which is longer than the specified 1
Created a chunk of size 257, which is longer than the specified 1
Created a chunk of size 304, which is longer than the specified 1
Created a chunk of size 614, which is longer than the specified 1
Created a chunk of size 419, which is longer than the specified 1
Created a chunk of size 887, which is longer than the specified 1
Created a chunk of size 693, which is longer than the specified 1
Created a chunk of size 302, which is longer than the specified 1
Created a chunk of size 217, which is longer than the specified 1
Created a chunk of size 269, which is longer than the specified 1
Created a chunk of size 2006, which is longer than the specified 1
Created a chunk of size 173, which is longer than the specified 1
Created a chunk of size 479, which is longer than the specified 1
Created a chunk of size 300, which is longer than the specified 1
Created a chunk of size 520, which is longer than the specified 1
Created a chunk of size 647, which is longer than the specified 1
Created a chunk of size 770, which is longer than the specified 1
Created a chunk of size 165, which is longer than the specified 1
Created a chunk of size 686, which is longer than the specified 1
Created a chunk of size 548, which is longer than the specified 1
Created a chunk of size 1222, which is longer than the specified 1
Created a chunk of size 406, which is longer than the specified 1
Created a chunk of size 1184, which is longer than the specified 1
Created a chunk of size 1214, which is longer than the specified 1
Created a chunk of size 1191, which is longer than the specified 1
Created a chunk of size 1057, which is longer than the specified 1
Created a chunk of size 244, which is longer than the specified 1
Created a chunk of size 688, which is longer than the specified 1
Created a chunk of size 876, which is longer than the specified 1
Created a chunk of size 284, which is longer than the specified 1
Created a chunk of size 766, which is longer than the specified 1
Created a chunk of size 385, which is longer than the specified 1
Created a chunk of size 417, which is longer than the specified 1
Created a chunk of size 208, which is longer than the specified 1
Created a chunk of size 206, which is longer than the specified 1
Created a chunk of size 723, which is longer than the specified 1
Created a chunk of size 209, which is longer than the specified 1
Created a chunk of size 163, which is longer than the specified 1
Created a chunk of size 526, which is longer than the specified 1
Created a chunk of size 521, which is longer than the specified 1
Created a chunk of size 214, which is longer than the specified 1
Created a chunk of size 338, which is longer than the specified 1
Created a chunk of size 899, which is longer than the specified 1
Created a chunk of size 1270, which is longer than the specified 1
Created a chunk of size 558, which is longer than the specified 1
Created a chunk of size 1635, which is longer than the specified 1
Created a chunk of size 436, which is longer than the specified 1
Created a chunk of size 249, which is longer than the specified 1
Created a chunk of size 777, which is longer than the specified 1
Created a chunk of size 716, which is longer than the specified 1
Created a chunk of size 514, which is longer than the specified 1
Created a chunk of size 958, which is longer than the specified 1
Created a chunk of size 198, which is longer than the specified 1
Created a chunk of size 1128, which is longer than the specified 1
Created a chunk of size 168, which is longer than the specified 1
Created a chunk of size 1319, which is longer than the specified 1
Created a chunk of size 851, which is longer than the specified 1
Created a chunk of size 272, which is longer than the specified 1
Created a chunk of size 795, which is longer than the specified 1
Created a chunk of size 1119, which is longer than the specified 1
Created a chunk of size 836, which is longer than the specified 1
Created a chunk of size 260, which is longer than the specified 1
Created a chunk of size 235, which is longer than the specified 1
Created a chunk of size 732, which is longer than the specified 1
Created a chunk of size 1189, which is longer than the specified 1
Created a chunk of size 710, which is longer than the specified 1
Created a chunk of size 773, which is longer than the specified 1
Created a chunk of size 278, which is longer than the specified 1
Created a chunk of size 307, which is longer than the specified 1
Created a chunk of size 356, which is longer than the specified 1
Created a chunk of size 766, which is longer than the specified 1
Created a chunk of size 762, which is longer than the specified 1
Created a chunk of size 716, which is longer than the specified 1
Created a chunk of size 2008, which is longer than the specified 1
Created a chunk of size 308, which is longer than the specified 1
Created a chunk of size 1286, which is longer than the specified 1
Created a chunk of size 1225, which is longer than the specified 1
Created a chunk of size 725, which is longer than the specified 1
Created a chunk of size 746, which is longer than the specified 1
Created a chunk of size 445, which is longer than the specified 1
Created a chunk of size 1236, which is longer than the specified 1
Created a chunk of size 309, which is longer than the specified 1
Created a chunk of size 912, which is longer than the specified 1
Created a chunk of size 304, which is longer than the specified 1
Created a chunk of size 844, which is longer than the specified 1
Created a chunk of size 1126, which is longer than the specified 1
Created a chunk of size 1073, which is longer than the specified 1
Created a chunk of size 1318, which is longer than the specified 1
Created a chunk of size 361, which is longer than the specified 1
Created a chunk of size 2826, which is longer than the specified 1
Created a chunk of size 233, which is longer than the specified 1
Created a chunk of size 240, which is longer than the specified 1
Created a chunk of size 171, which is longer than the specified 1
Created a chunk of size 204, which is longer than the specified 1
Created a chunk of size 570, which is longer than the specified 1
Created a chunk of size 206, which is longer than the specified 1
Created a chunk of size 363, which is longer than the specified 1
Created a chunk of size 1141, which is longer than the specified 1
Created a chunk of size 1004, which is longer than the specified 1
Created a chunk of size 711, which is longer than the specified 1
Created a chunk of size 710, which is longer than the specified 1
Created a chunk of size 2504, which is longer than the specified 1
Created a chunk of size 954, which is longer than the specified 1
Created a chunk of size 307, which is longer than the specified 1
Created a chunk of size 347, which is longer than the specified 1
Created a chunk of size 639, which is longer than the specified 1
Created a chunk of size 401, which is longer than the specified 1
Created a chunk of size 523, which is longer than the specified 1
Created a chunk of size 793, which is longer than the specified 1
Created a chunk of size 165, which is longer than the specified 1
Created a chunk of size 389, which is longer than the specified 1
Created a chunk of size 254, which is longer than the specified 1
Created a chunk of size 1422, which is longer than the specified 1
Created a chunk of size 1083, which is longer than the specified 1
Created a chunk of size 1144, which is longer than the specified 1
Created a chunk of size 1262, which is longer than the specified 1
Created a chunk of size 784, which is longer than the specified 1
Created a chunk of size 293, which is longer than the specified 1
Created a chunk of size 1086, which is longer than the specified 1
Created a chunk of size 870, which is longer than the specified 1
Created a chunk of size 250, which is longer than the specified 1
Created a chunk of size 870, which is longer than the specified 1
Created a chunk of size 806, which is longer than the specified 1
Created a chunk of size 1812, which is longer than the specified 1
Created a chunk of size 1826, which is longer than the specified 1
Created a chunk of size 1060, which is longer than the specified 1
Created a chunk of size 951, which is longer than the specified 1
Created a chunk of size 1180, which is longer than the specified 1
Created a chunk of size 281, which is longer than the specified 1
Created a chunk of size 281, which is longer than the specified 1
Created a chunk of size 286, which is longer than the specified 1
Created a chunk of size 1284, which is longer than the specified 1
Created a chunk of size 1642, which is longer than the specified 1
Created a chunk of size 757, which is longer than the specified 1
Created a chunk of size 1930, which is longer than the specified 1
Created a chunk of size 872, which is longer than the specified 1
Created a chunk of size 2000, which is longer than the specified 1
Created a chunk of size 2281, which is longer than the specified 1
Created a chunk of size 173, which is longer than the specified 1
Created a chunk of size 997, which is longer than the specified 1
Created a chunk of size 577, which is longer than the specified 1
Created a chunk of size 288, which is longer than the specified 1
Created a chunk of size 255, which is longer than the specified 1
Created a chunk of size 1142, which is longer than the specified 1
Created a chunk of size 557, which is longer than the specified 1
Created a chunk of size 1137, which is longer than the specified 1
Created a chunk of size 243, which is longer than the specified 1
Created a chunk of size 1086, which is longer than the specified 1
Created a chunk of size 1479, which is longer than the specified 1
Created a chunk of size 221, which is longer than the specified 1
Created a chunk of size 1135, which is longer than the specified 1
Created a chunk of size 722, which is longer than the specified 1
Created a chunk of size 664, which is longer than the specified 1
Created a chunk of size 765, which is longer than the specified 1
Created a chunk of size 606, which is longer than the specified 1
Created a chunk of size 570, which is longer than the specified 1
Created a chunk of size 965, which is longer than the specified 1
Created a chunk of size 857, which is longer than the specified 1
Created a chunk of size 1032, which is longer than the specified 1
Created a chunk of size 189, which is longer than the specified 1
Created a chunk of size 367, which is longer than the specified 1
Created a chunk of size 495, which is longer than the specified 1
Created a chunk of size 648, which is longer than the specified 1
Created a chunk of size 348, which is longer than the specified 1
Created a chunk of size 733, which is longer than the specified 1
Created a chunk of size 525, which is longer than the specified 1
Created a chunk of size 1015, which is longer than the specified 1
Created a chunk of size 970, which is longer than the specified 1
Created a chunk of size 204, which is longer than the specified 1
Created a chunk of size 688, which is longer than the specified 1
Created a chunk of size 544, which is longer than the specified 1
Created a chunk of size 242, which is longer than the specified 1
Created a chunk of size 207, which is longer than the specified 1
Created a chunk of size 376, which is longer than the specified 1
Created a chunk of size 931, which is longer than the specified 1
Created a chunk of size 560, which is longer than the specified 1
Created a chunk of size 854, which is longer than the specified 1
Created a chunk of size 715, which is longer than the specified 1
Created a chunk of size 745, which is longer than the specified 1
Created a chunk of size 712, which is longer than the specified 1
Created a chunk of size 324, which is longer than the specified 1
Created a chunk of size 241, which is longer than the specified 1
Created a chunk of size 1088, which is longer than the specified 1
Created a chunk of size 723, which is longer than the specified 1
Created a chunk of size 245, which is longer than the specified 1
Created a chunk of size 227, which is longer than the specified 1
Created a chunk of size 704, which is longer than the specified 1
Created a chunk of size 1912, which is longer than the specified 1
Created a chunk of size 395, which is longer than the specified 1
Created a chunk of size 485, which is longer than the specified 1
Created a chunk of size 618, which is longer than the specified 1
Created a chunk of size 559, which is longer than the specified 1
Created a chunk of size 556, which is longer than the specified 1
Created a chunk of size 386, which is longer than the specified 1
Created a chunk of size 229, which is longer than the specified 1
Created a chunk of size 425, which is longer than the specified 1
Created a chunk of size 414, which is longer than the specified 1
Created a chunk of size 284, which is longer than the specified 1
Created a chunk of size 166, which is longer than the specified 1
Created a chunk of size 624, which is longer than the specified 1
Created a chunk of size 2608, which is longer than the specified 1
Created a chunk of size 1574, which is longer than the specified 1
Created a chunk of size 389, which is longer than the specified 1
Created a chunk of size 994, which is longer than the specified 1
Created a chunk of size 847, which is longer than the specified 1
Created a chunk of size 263, which is longer than the specified 1
Created a chunk of size 336, which is longer than the specified 1
Created a chunk of size 1524, which is longer than the specified 1
Created a chunk of size 213, which is longer than the specified 1
Created a chunk of size 287, which is longer than the specified 1
Created a chunk of size 2030, which is longer than the specified 1
Created a chunk of size 396, which is longer than the specified 1
Created a chunk of size 1612, which is longer than the specified 1
Created a chunk of size 698, which is longer than the specified 1
Created a chunk of size 822, which is longer than the specified 1
Created a chunk of size 354, which is longer than the specified 1
Created a chunk of size 839, which is longer than the specified 1
Created a chunk of size 1189, which is longer than the specified 1
Created a chunk of size 195, which is longer than the specified 1
Created a chunk of size 508, which is longer than the specified 1
Created a chunk of size 663, which is longer than the specified 1
Created a chunk of size 1282, which is longer than the specified 1
Created a chunk of size 260, which is longer than the specified 1
Created a chunk of size 242, which is longer than the specified 1
Created a chunk of size 215, which is longer than the specified 1
Created a chunk of size 198, which is longer than the specified 1
Created a chunk of size 1262, which is longer than the specified 1
Created a chunk of size 1271, which is longer than the specified 1
Created a chunk of size 198, which is longer than the specified 1
Created a chunk of size 1056, which is longer than the specified 1
Created a chunk of size 378, which is longer than the specified 1
Created a chunk of size 269, which is longer than the specified 1
Created a chunk of size 177, which is longer than the specified 1
Created a chunk of size 225, which is longer than the specified 1
Created a chunk of size 222, which is longer than the specified 1
Created a chunk of size 778, which is longer than the specified 1
Created a chunk of size 969, which is longer than the specified 1
Created a chunk of size 613, which is longer than the specified 1
Created a chunk of size 163, which is longer than the specified 1
Created a chunk of size 757, which is longer than the specified 1
Created a chunk of size 289, which is longer than the specified 1
Created a chunk of size 245, which is longer than the specified 1
Created a chunk of size 963, which is longer than the specified 1
Created a chunk of size 232, which is longer than the specified 1
Created a chunk of size 843, which is longer than the specified 1
Created a chunk of size 786, which is longer than the specified 1
Created a chunk of size 648, which is longer than the specified 1
Created a chunk of size 984, which is longer than the specified 1
Created a chunk of size 795, which is longer than the specified 1
Created a chunk of size 193, which is longer than the specified 1
Created a chunk of size 1159, which is longer than the specified 1
Created a chunk of size 253, which is longer than the specified 1
Created a chunk of size 199, which is longer than the specified 1
Created a chunk of size 1054, which is longer than the specified 1
Created a chunk of size 246, which is longer than the specified 1
Created a chunk of size 875, which is longer than the specified 1

In [10]:
documents[0]

Document(metadata={'source': 'tagged_description.txt'}, page_content='9780002005883 A NOVEL THAT READERS and critics have been eagerly anticipating for over a decade, Gilead is an astonishingly imagined story of remarkable lives. John Ames is a preacher, the son of a preacher and the grandson (both maternal and paternal) of preachers. It’s 1956 in Gilead, Iowa, towards the end of the Reverend Ames’s life, and he is absorbed in recording his family’s story, a legacy for the young son he will never see grow up. Haunted by his grandfather’s presence, John tells of the rift between his grandfather and his father: the elder, an angry visionary who fought for the abolitionist cause, and his son, an ardent pacifist. He is troubled, too, by his prodigal namesake, Jack (John Ames) Boughton, his best friend’s lost son who returns to Gilead searching for forgiveness and redemption. Told in John Ames’s joyous, rambling voice that finds beauty, humour and truth in the smallest of life’s details, Gilead is a song of celebration and acceptance of the best and the worst the world has to offer. At its heart is a tale of the sacred bonds between fathers and sons, pitch-perfect in style and story, set to dazzle critics and readers alike.')

## Use "OllamaEmbeddings" to create a DB of words

In [14]:
from langchain_chroma import Chroma
from langchain_ollama import OllamaEmbeddings
db_books = Chroma.from_documents(
    documents,
    embedding=OllamaEmbeddings(
        model="mxbai-embed-large"
    )
    )

## Trying a query of 10 to search similarity in DB

In [20]:
query = "A book to teach children about nature"
docs = db_books.similarity_search(query, k = 10)
docs

[Document(id='bdc8dab1-b512-43ce-90d3-240667585b2b', metadata={'source': 'tagged_description.txt'}, page_content='9780786808069 Children will discover the exciting world of their own backyard in this introduction to familiar animals from cats and dogs to bugs and frogs. The combination of photographs, illustrations, and fun facts make this an accessible and delightful learning experience.'),
 Document(id='bf436344-ea90-41a0-91e3-3aeaedd627ec', metadata={'source': 'tagged_description.txt'}, page_content='9780067575208 First published more than three decades ago, this reissue of Rachel Carson\'s award-winning classic brings her unique vision to a new generation of readers. Stunning new photographs by Nick Kelsh beautifully complement Carson\'s intimate account of adventures with her young nephew, Roger, as they enjoy walks along the rocky coast of Maine and through dense forests and open fields, observing wildlife, strange plants, moonlight and storm clouds, and listening to the "living music" of insects in the underbrush. "If a child is to keep alive his inborn sense of wonder." Writes Carson, "he needs the companionship of at least one adult who can share it, rediscovering with him the joy, excitement and mystery of the world we live in." The Sense of Wonder is a refreshing antidote to indifference and a guide to capturing the simple power of discovery that Carson views as essential to life. In her insightful new introduction, Linda Lear remembers Rachel Carson\'s groundbreaking achievements in the context of the legendary environmentalist\'s personal commitment to introducing young and old to the miracles of nature. Kelsh\'s lush photographs inspire sensual, tactile reactions: masses of leaves floating in a puddle are just waiting to be scooped up and examined more closely. An image of a narrow path through the trees evokes the earthy scent of the woods after a summer rain. Close-ups of mosses and miniature lichen fantasy-lands will spark innocent\'as well as more jaded\'imaginations. Like a curious child studying things underfoot and within reach, Kelsh\'s camera is drawn to patterns in nature that too often elude hurried adults\'a stand of beech trees in the springtime, patches of melting snow and the ripples from a pebble tossed into a slow-moving stream. The Sense of Wonder is a timeless volume that will be passed on from children to grandchildren, as treasured as the memory of an early-morning walk when the song of a whippoorwill was heard as if for the first time.'),
 Document(id='1ec27e2c-db65-4226-a7e8-9e1798d06fd4', metadata={'source': 'tagged_description.txt'}, page_content='9780763620875 When Judy Moody gets serious about protecting the environment, her little brother Stink thinks she is overdoing it, but she manages to inspire her third grade class to undertake an award-winning, environment-saving project. Reprint.'),
 Document(id='3a6961b3-76f0-48a2-9eb1-a1c333d9e3a6', metadata={'source': 'tagged_description.txt'}, page_content='9780143037392 Explains the importance of reading aloud to children, offers guidance on how to set up a read-aloud atmosphere in the home or classroom, and recommends titles to select.'),
 Document(id='c8171914-5532-44b1-8c7d-519c61c8180c', metadata={'source': 'tagged_description.txt'}, page_content="9780786808380 Introduce your babies to birds, cats, dogs, and babies through fine art, illustration, and photographs. These books are a rare opportunity to expose little ones to a range of images on a single subject, from simple child's drawings and abstract art to playful photos. A brief text accompanies each image, introducing the baby to some basic -- and sometimes playful -- information about the subjects."),
 Document(id='bc60e098-7f1e-48aa-8459-49d20f834d22', metadata={'source': 'tagged_description.txt'}, page_content='9780789458209 Photographs and text explore the anatomy and life cycle of trees, examining the different kinds of bark, seeds, and leaves, the commercial processing of trees to make lumber, the creatures that live in trees, and other aspects.'),
 Document(id='5f409671-4463-4b7c-8511-fefab59c3162', metadata={'source': 'tagged_description.txt'}, page_content='9780064434980 Even the youngest child can enjoy a special adaptation of a classic Little House tale, as Laura and Mary listen to Pa talk about meeting a mother deer and her baby fawn deep in the Big Woods of Wisconsin.'),
 Document(id='86e750f5-8b22-4022-a039-1ba708145aa2', metadata={'source': 'tagged_description.txt'}, page_content="9780786808373 Introducing your baby to birds, cats, dogs, and babies through fine art, illsutration and photographs. These books are a rare opportunity to expose little ones to a range of images on a single subject, from simple child's drawings and abstract art to playful photos. A brief text accompanies each image, introducing baby to some basic -- and sometimes playful -- information on the subjects."),
 Document(id='deb9c88e-3bbc-4856-8372-f8e2d6daa254', metadata={'source': 'tagged_description.txt'}, page_content="9780786808397 Introduce your baby to birds, cats, dogs, and babies through fine art, illustration, and photographs. These books are a rare opportunity to exopse little ones to a range of images on a single subject, from simple child's drawings and abstract art to playful photos. A brief text accompanies each image, introducing baby to some basic -- and sometimes playful -- information about the subjects."),
 Document(id='5d2497cc-f243-4a19-9518-bdea0cf3056c', metadata={'source': 'tagged_description.txt'}, page_content='9780689716041 An eight-year-old boy who is frightened of traveling over Hemlock Mountain overcomes his fear by taking the trip while chanting, "There are no bears on Hemlock Mountain," in a suspenseful tale. Reissue.')]

## Trying a query of 10 to search similarity with CSV and DB

In [27]:
books[books["isbn13"] == int(docs[0].page_content.split()[0].strip('"'))]

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description
3747,9780786808069,0786808063,Baby Einstein: Neighborhood Animals,Marilyn Singer;Julie Aigner-Clark,Juvenile Fiction,http://books.google.com/books/content?id=X9a4P...,Children will discover the exciting world of t...,2001.0,3.89,16.0,180.0,Baby Einstein: Neighborhood Animals,9780786808069 Children will discover the excit...

In [ ]:
def retrieve_semantic_recommendations(
        query: str,
        top_k: int = 10,
) -> pd.DataFrame:
    recs = db_books.similarity_search(query, k = 50)

    books_list = []

    for i in range(0, len(recs)):
        books_list += [int(recs[i].page_content.strip('"').split()[0])]

    return books[books["isbn13"].isin(books_list)]

In [25]:
retrieve_semantic_recommendations("A book to teach children about nature")

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description
59,9780007151240,0007151241,The Family Way,Tony Parsons,Parenthood,http://books.google.com/books/content?id=dJEIx...,It should be the most natural thing in the wor...,2005.0,3.51,400.0,2095.0,The Family Way,9780007151240 It should be the most natural th...
143,9780060546571,0060546573,Three Rotten Eggs,Gregory Maguire,Juvenile Fiction,http://books.google.com/books/content?id=t2pWl...,The students of Miss Earth's class in rural Ve...,2005.0,3.74,240.0,76.0,Three Rotten Eggs,9780060546571 The students of Miss Earth's cla...
146,9780060556501,0060556501,"The Lion, the Witch and the Wardrobe (picture ...",C. S. Lewis,Juvenile Fiction,http://books.google.com/books/content?id=FlSpp...,Narnia: A magical land full of wonder and exci...,2004.0,4.19,48.0,5012.0,"The Lion, the Witch and the Wardrobe (picture ...",9780060556501 Narnia: A magical land full of w...
223,9780060775858,0060775858,Goodnight Moon 60th Anniversary Edition,Margaret Wise Brown,Juvenile Fiction,http://books.google.com/books/content?id=lLYOr...,"In a great green room, tucked away in bed, is ...",2005.0,4.27,32.0,264013.0,Goodnight Moon 60th Anniversary Edition,"9780060775858 In a great green room, tucked aw..."
324,9780060959036,0060959037,Prodigal Summer,Barbara Kingsolver,Fiction,http://books.google.com/books/content?id=06IwG...,Barbara Kingsolver's fifth novel is a hymn to ...,2001.0,4.00,444.0,85440.0,Prodigal Summer: A Novel,9780060959036 Barbara Kingsolver's fifth novel...
368,9780061127762,0061127760,Charlotte's Web Signature Edition,E. B. White,Juvenile Fiction,http://books.google.com/books/content?id=oi9BP...,This is the story of a little girl named Fern ...,2006.0,4.16,224.0,226.0,Charlotte's Web Signature Edition,9780061127762 This is the story of a little gi...
373,9780061131622,0061131628,Mandy,Julie Andrews Edwards,Juvenile Fiction,http://books.google.com/books/content?id=5dNj_...,"Mandy, a ten-year-old orphan, dreams of a plac...",2006.0,4.24,320.0,9482.0,Mandy,"9780061131622 Mandy, a ten-year-old orphan, dr..."
406,9780064403870,0064403874,"R-T, Margaret, and the Rats of NIMH",Jane Leslie Conly,Juvenile Fiction,http://books.google.com/books/content?id=WTHHH...,"When Margaret and her younger brother, Artie, ...",1991.0,3.52,272.0,631.0,"R-T, Margaret, and the Rats of NIMH",9780064403870 When Margaret and her younger br...
427,9780064434874,0064434877,Christmas in the Big Woods,Laura Ingalls Wilder,Juvenile Fiction,http://books.google.com/books/content?id=FT1Yp...,"Long ago, a little girl named Laura Ingalls li...",1997.0,4.19,32.0,2062.0,Christmas in the Big Woods,"9780064434874 Long ago, a little girl named La..."
429,9780064434980,0064434982,The Deer in the Wood,Laura Ingalls Wilder,Juvenile Fiction,http://books.google.com/books/content?id=V7YDW...,Even the youngest child can enjoy a special ad...,1999.0,4.17,32.0,302.0,The Deer in the Wood,9780064434980 Even the youngest child can enjo...
430,9780064435260,0064435261,A Little Prairie House,Laura Ingalls Wilder,Juvenile Fiction,http://books.google.com/books/content?id=pRSju...,"Long, long ago, a little girl named Laura Inga...",1999.0,4.19,32.0,1533.0,A Little Prairie House,"9780064435260 Long, long ago, a little girl na..."
442,9780067575208,006757520X,The Sense of Wonder,Rachel Carson,Nature,http://books.google.com/books/content?id=Zee5S...,"First published more than three decades ago, t...",1998.0,4.39,112.0,1160.0,The Sense of Wonder,9780067575208 First published more than three ...
855,9780143037392,0143037390,The Read-aloud Handbook,Jim Trelease,Language Arts & Disciplines,http://books.google.com/books/content?id=B2_yU...,Explains the importance of reading aloud to ch...,2006.0,4.40,432.0,4122.0,The Read-aloud Handbook,9780143037392 Explains the importance of readi...
1078,9780241003008,0241003008,The Very Hungry Caterpillar,Eric Carle,Babytime resource,http://books.google.com/books/content?id=DpGEQ...,Eric Carle's children's classic is the story o...,1994.0,4.29,26.0,340101.0,The Very Hungry Caterpillar,9780241003008 Eric Carle's children's classic ...
1109,9780285647879,0285647873,The Wanderer,Knut Hamsun;Gunnvor Stallybrass,English fiction,http://books.google.com/books/content?id=RU1_Q...,It has always been a pleasure to me to watch t...,2001.0,3.96,164.0,672.0,The Wanderer,9780285647879 It has always been a pleasure to...
1247,9780312369347,0312369344,Beatrix Potter,Linda Lear,Biography & Autobiography,http://books.google.com/books/content?id=T9uTx...,"Peter Rabbit, Mr. McGregor, and many other Bea...",2007.0,4.03,584.0,1270.0,Beatrix Potter: A Life in Nature,"9780312369347 Peter Rabbit, Mr. McGregor, and ..."
1639,9780374422080,0374422087,Everything on a Waffle,Polly Horvath,Juvenile Fiction,http://books.google.com/books/content?id=NimVJ...,This Newbery Honor Book tells the story of 11 ...,2004.0,3.71,150.0,9631.0,Everything on a Waffle,9780374422080 This Newbery Honor Book tells th...
1738,9780375806704,0375806709,The Phantom Tollbooth,Norton Juster,Fantasy fiction,http://books.google.com/books/content?id=BZ2pP...,"For Milo, everything's a bore. When a tollboot...",2000.0,4.21,256.0,866.0,The Phantom Tollbooth,"9780375806704 For Milo, everything's a bore. W..."
1739,9780375812934,0375812938,Jurassic Park Institute Dinosaur Field Guide,Thomas R. Holtz;M. K. Brett-Surman,Juvenile Nonfiction,http://books.google.com/books/content?id=vW3hm...,Discusses dinosaur research and what can be le...,2001.0,4.08,160.0,2.0,Jurassic Park Institute Dinosaur Field Guide,9780375812934 Discusses dinosaur research and ...
1907,9780393315110,0393315118,Uncommon Ground: Rethinking the Human Place in...,William Cronon,Law,http://books.google.com/books/content?id=w04mj...,"Essays by revisionist historians, scientists, ...",1996.0,4.16,560.0,649.0,Uncommon Ground: Rethinking the Human Place in...,9780393315110 Essays by revisionist historians...
2216,9780440421702,0440421705,Hoot,Carl Hiaasen,Bullying,http://books.google.com/books/content?id=uKUTo...,"Roy, who is new to his small Florida community...",2006.0,3.82,292.0,83557.0,Hoot,"9780440421702 Roy, who is new to his small Flo..."
2410,9780451457592,0451457595,The River's Gift,Mercedes Lackey,Fiction,http://books.google.com/books/content?id=qLonv...,Fifteen-year-old Ariella spends her days in th...,1999.0,3.88,128.0,1029.0,The River's Gift,9780451457592 Fifteen-year-old Ariella spends ...
2659,9780553112443,0553112449,Switch on the Night,Ray Bradbury;Leo Dillon;Diane Dillon,Juvenile Fiction,http://books.google.com/books/content?id=1eUMA...,When a magical little girl named Dark shows a ...,2004.0,4.09,40.0,186.0,Switch on the Night,9780553112443 When a magical little girl named...
2668,9780553213973,0553213970,Journey To The Center Of The Earth,Jules Verne,Fiction,http://books.google.com/books/content?id=4_dvD...,"Follows Professor Hardwigg, his nephew Harry, ...",2006.0,3.85,240.0,101764.0,Journey To The Center Of The Earth,"9780553213973 Follows Professor Hardwigg, his ..."
2887,9780618056736,0618056734,Unweaving the Rainbow,Richard Dawkins,Science,http://books.google.com/books/content?id=GWj0q...,"Offers an assessment of what science is, how i...",2000.0,4.02,352.0,9168.0,"Unweaving the Rainbow: Science, Delusion and t...",9780618056736 Offers an assessment of what sci...
3000,9780671631987,0671631985,Teach Your Child to Read in 100 Easy Lessons,Siegfried Engelmann;Phyllis Haddox;Elaine Bruner,Education,http://books.google.com/books/content?id=MUucJ...,"With more than half a million copies in print,...",1986.0,4.15,395.0,2083.0,Teach Your Child to Read in 100 Easy Lessons,9780671631987 With more than half a million co...
3198,9780689716041,0689716044,The Bears on Hemlock Mountain,Alice Dalgliesh,Juvenile Fiction,http://books.google.com/books/content?id=2gt4h...,An eight-year-old boy who is frightened of tra...,1992.0,3.78,64.0,2017.0,The Bears on Hemlock Mountain,9780689716041 An eight-year-old boy who is fri...
3201,9780689823824,0689823827,A Child's Garden of Verses,Robert Louis Stevenson,Juvenile Fiction,http://books.google.com/books/content?id=luTZA...,"Here is a delightful look at childhood, writte...",1999.0,4.30,67.0,21780.0,A Child's Garden of Verses,9780689823824 Here is a delightful look at chi...
3442,9780744578263,0744578264,The Sea-thing Child,Russell Hoban,Birds,http://books.google.com/books/content?id=CEt9O...,"Washed up on the beach during a storm, the sea...",2000.0,3.79,48.0,100.0,The Sea-thing Child,9780744578263 Washed up on the beach during a ...
3581,9780763620875,0763620874,Judy Moody Saves the World!,Megan McDonald,Juvenile Fiction,http://books.google.com/books/content?id=xDIRB...,When Judy Moody gets serious about protecting ...,2004.0,4.03,160.0,5883.0,Judy Moody Saves the World!,9780763620875 When Judy Moody gets serious abo...
3591,9780764122781,0764122789,Aquatic Turtles,Richard D. Bartlett;Patricia Bartlett,Pets,http://books.google.com/books/content?id=ket2b...,Titles in this series present basic informatio...,2003.0,3.80,46.0,20.0,"Aquatic Turtles: Sliders, Cooters, Painted, an...",9780764122781 Titles in this series present ba...
3747,9780786808069,0786808063,Baby Einstein: Neighborhood Animals,Marilyn Singer;Julie Aigner-Clark,Juvenile Fiction,http://books.google.com/books/content?id=X9a4P...,Children will discover the exciting world of t...,2001.0,3.89,16.0,180.0,Baby Einstein: Neighborhood Animals,9780786808069 Children will discover the excit...
3748,9780786808373,0786808373,Baby Einstein: Birds,Julie Aigner-Clark,Juvenile Fiction,http://books.google.com/books/content?id=0jxHP...,"Introducing your baby to birds, cats, dogs, an...",2002.0,3.78,20.0,9.0,Baby Einstein: Birds,"9780786808373 Introducing your baby to birds, ..."
3749,9780786808380,0786808381,Baby Einstein: Babies,Julie Aigner-Clark,Juvenile Fiction,http://books.google.com/books/content?id=jv4NA...,"Introduce your babies to birds, cats, dogs, an...",2002.0,4.03,20.0,29.0,Baby Einstein: Babies,"9780786808380 Introduce your babies to birds, ..."
3750,9780786808397,078680839X,Baby Einstein: Dogs,Julie Aigner-Clark,Juvenile Fiction,http://books.google.com/books/content?id=qut8t...,"Introduce your baby to birds, cats, dogs, and ...",2002.0,3.81,20.0,26.0,Baby Einstein: Dogs,"9780786808397 Introduce your baby to birds, ca..."
3751,9780786808717,0786808713,Baby Einstein: What Does Violet See? Raindrops...,Julie Aigner-Clark,Juvenile Fiction,http://books.google.com/books/content?id=95IIA...,A very special puddle sets Violet the mouse of...,2002.0,3.25,18.0,16.0,Baby Einstein: What Does Violet See? Raindrops...,9780786808717 A very special puddle sets Viole...
3756,9780786809608,0786809604,"If I Have a Wicked Stepmother, Where's My Prince?",Melissa Kantor,Juvenile Fiction,http://books.google.com/books/content?id=cS5XG...,"Mrs. McBloom, clean up your room!""For nearly f...",2005.0,3.66,283.0,4337.0,"If I Have a Wicked Stepmother, Where's My Prince?","9780786809608 Mrs. McBloom, clean up your room..."
3760,9780786812912,0786812915,The Big Box,Toni Morrison;Slade Morrison,Juvenile Fiction,http://books.google.com/books/content?id=LyYKA...,"In her first illustrated book for children, th...",2002.0,3.95,48.0,375.0,The Big Box,9780786812912 In her first illustrated book fo...
3765,9780786819119,0786819111,"Baby Einstein: Water, Water Everywhere","Disney Book Group,",Juvenile Fiction,http://books.google.com/books/content?id=tuAdA...,Charming illustrations and playful rhythmic ve...,2003.0,3.70,10.0,77.0,"Baby Einstein: Water, Water Everywhere",9780786819119 Charming illustrations and playf...
3797,9780789458209,0789458209,Tree,David Burnie,Juvenile Nonfiction,http://books.google.com/books/content?id=Qwsqj...,Photographs and text explore the anatomy and l...,2000.0,4.07,64.0,5.0,Tree,9780789458209 Photographs and text explore the...
4231,9780898599596,0898599598,The Ecological Approach to Visual Perception,James Jerome Gibson,Psychology,http://books.google.com/books/content?id=DrhCC...,This is a book about how we see: the environme...,1986.0,4.28,348.0,122.0,The Ecological Approach to Visual Perception,9780898599596 This is a book about how we see:...
4256,9780939666508,0939666502,Yosemite,Margaret Sanborn,History,http://books.google.com/books/content?id=8zwJA...,"Recounts the history of Yosemite, covering the...",1989.0,3.96,289.0,23.0,"Yosemite: Its Discovery, Its Wonders and Its P...",9780939666508 Recounts the history of Yosemite...
4276,9780965738408,096573840X,A Short History of Nearly Everything,Bill Bryson,Science,NaN,In this book Bill Bryson explores the most int...,2003.0,4.20,545.0,28.0,A Short History of Nearly Everything: 7 Steps ...,9780965738408 In this book Bill Bryson explore...
4295,9780975323113,0975323113,Plants And Landscapes For Summer-dry Climates ...,East Bay Municipal Utility District (Calif.),Gardening,http://books.google.com/books/content?id=Dj2XN...,Gardening. Environmental Studies. Photographs ...,2004.0,4.33,336.0,46.0,Plants And Landscapes For Summer-dry Climates ...,9780975323113 Gardening. Environmental Studies...
4302,9780976882305,0976882302,The Giraffe who was Afraid of Heights,David A. Ufer,Juvenile Fiction,http://books.google.com/books/content?id=j2IzK...,This is a facinating tale about a young giraff...,2006.0,3.81,32.0,34.0,The Giraffe who was Afraid of Heights,9780976882305 This is a facinating tale about ...
4331,9781400033850,1400033853,Providence of a Sparrow,Chris Chester,Biography & Autobiography,http://books.google.com/books/content?id=Z7RDD...,Describes the influence of a foundling baby sp...,2004.0,4.32,304.0,218.0,Providence of a Sparrow: Lessons from a Life G...,9781400033850 Describes the influence of a fou...
4360,9781400051571,1400051576,The Last Hours of Ancient Sunlight,Thom Hartmann,Political Science,http://books.google.com/books/content?id=7d4VD...,A revised edition of a landmark study offers a...,2004.0,4.22,400.0,1341.0,The Last Hours of Ancient Sunlight: The Fate o...,9781400051571 A revised edition of a landmark ...
4455,9781405201711,1405201711,The Faraway Tree Stories,Enid Blyton,"Children's stories, English",http://books.google.com/books/content?id=2d93O...,"Jo, Bessie and Fanny move to the country and f...",1987.0,4.29,583.0,12286.0,The Faraway Tree Stories,"9781405201711 Jo, Bessie and Fanny move to the..."
4541,9781421509594,1421509598,The Drifting Classroom,Kazuo Umezu,Comics & Graphic Novels,http://books.google.com/books/content?id=6ME-P...,A flash flood turns the desert into a drowned ...,2007.0,3.94,192.0,311.0,The Drifting Classroom,9781421509594 A flash flood turns the desert i...
4831,9781590171240,1590171241,An Episode of Sparrows,Rumer Godden,Juvenile Fiction,http://books.google.com/books/content?id=wLgdp...,"In post-World War II London, two street-tough ...",2004.0,4.20,247.0,851.0,An Episode of Sparrows: A Novel,"9781590171240 In post-World War II London, two..."